name: Third Workflow 

on:
  push:
    branches:
      - main

jobs:
  check hostname:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: check hostname
        run: hostname
